---
- name: Create directories
  file:
    dest: "{{ item }}"
    state: directory
  loop:
    - "{{ nextcloud_docker_project_dir }}"
    - "{{ nextcloud_config_dir }}"
    - "{{ nextcloud_backup_dir }}"
    - "{{ nextcloud_backup_data_dir }}"

- name: Create environment
  block:
    - template:
        dest: "{{ nextcloud_docker_project_dir }}"
        src: templates/docker-compose.yml
    - template:
        dest: "{{ nextcloud_docker_project_dir }}"
        src: templates/.env

- name: Install backup pre-script
  become: yes
  template:
    src: templates/backup_pre_hook.sh
    dest: "{{ borg_scripts_root }}/backup_nextcloud_pre.sh"
    mode: +x

- name: Install restore script
  become: yes
  template:
    src: templates/restore_post_hook.sh
    dest: "{{ borg_scripts_root }}/restore_nextcloud_post.sh"
    mode: +x