---
- name: Create root directory
  become: yes
  file:
    dest: "{{ nextcloud_root_dir }}"
    state: directory
    group: www-data

- name: Create directories
  file:
    dest: "{{ item }}"
    state: directory
  loop:
    - "{{ nextcloud_docker_base_dir }}"
    - "{{ nextcloud_config_dir }}"

- name: Create environment
  block:
    - copy:
        dest: "{{ nextcloud_docker_base_dir }}"
        src: files/docker-compose.yml
    - template:
        dest: "{{ nextcloud_docker_base_dir }}"
        src: templates/.env
