version: '2'

volumes:
  root:
  data:
  apps:
  db:

networks:
  nextcloud:

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - nextcloud
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    ports:
      - ${NEXTCLOUD_EXTERNAL_PORT}:80
    depends_on:
      - db
    networks:
      - nextcloud
    volumes:
      - root:/var/www/html
      - apps:/var/www/html/custom_apps
      - ${NEXTCLOUD_CONFIG_DIR}:/var/www/html/config
      - data:/var/www/html/data
    restart: always
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_HOST=db:3306